### ISSUE TITLE
TODO: Implement simple tests

### ISSUE THREAD

**Issue by rfay** [rfay/ddev-ibexa_cloud#1]
The automated tests need at least some basic setup.
- [x] Test project needs to be left running or else we have to start it and wait for it (a decent option)
- [x] Create `pull` and `push` environments on test project
- [x] Check out the test project
- [x] Test pull and verify that we got db and files
- [x] Test push and verify that they went up

**Comment by rfay** [comment]
These are working
